# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'agapanto'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-173626706-1'

menu: 
  - name: Proyectos
    submenu:
      - name: Facturacion electronica
        link: /projects/tiendas-agapanto
      - name: Gestion documental
        link: /projects/documentos-agapanto
  - name: Publicaciones
    link: /
  - name: Etiquetas
    link: /tags
  - name: Información
    link: /about
  - name: Siguenos
    submenu:
      - name: GitHub
        icon: github
        link: http://github.com/sistemasagapanto
      - name: LinkedIn
        icon: linkedin-square
        link: http://www.linkedin.com/in/sistemas-agapanto-sas-86089a1b3
      - name: Twitter
        icon: twitter
        link: https://twitter.com/sistemasagapan1
    
